# Generated by Django 3.0.3 on 2020-04-01 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
